import Foundation

// swiftlint:disable type_body_length file_length

enum LocalSuggestionsData {

    static let suggestions: [LocalSuggestion] = restaurants + attractions

    // MARK: - Restaurants

    static let restaurants: [LocalSuggestion] = [
        // Orleans
        LocalSuggestion(id: "r-rock-harbor-grill", name: "Rock Harbor Grill", type: .restaurant, town: .orleans,
            rating: 4.6, reviewCount: 428, priceLevel: 2,
            description: "Casual seafood with stunning harbor sunset views. Known for fresh catch and local oysters.",
            topItems: ["Fish Tacos", "Lobster Roll", "Fried Clams", "Cape Cod Lager"],
            bestFor: "Waterfront dining", icon: "fork.knife"),
        LocalSuggestion(id: "r-nauset-beach-club", name: "Nauset Beach Club", type: .restaurant, town: .orleans,
            rating: 4.5, reviewCount: 612, priceLevel: 3,
            description: "Italian-Mediterranean meets Cape Cod seafood. Elegant yet relaxed atmosphere.",
            topItems: ["Lobster Fra Diavolo", "Grilled Swordfish", "Pasta Puttanesca", "Tiramisu"],
            bestFor: "Date night", icon: "fork.knife"),
        LocalSuggestion(id: "r-sundae-school-orleans", name: "Sundae School", type: .restaurant, town: .orleans,
            rating: 4.8, reviewCount: 890, priceLevel: 1,
            description: "Iconic Cape Cod ice cream shop. Homemade flavors with generous scoops since 1976.",
            topItems: ["Cookie Monster", "Black Raspberry", "Hot Fudge Sundae", "Frappe"],
            bestFor: "Family treats", icon: "fork.knife"),
        LocalSuggestion(id: "r-joes-beach-rd", name: "Joe's Beach Road Bar & Grille", type: .restaurant, town: .orleans,
            rating: 4.3, reviewCount: 315, priceLevel: 2,
            description: "Lively local spot with great burgers, craft beer, and live music on weekends.",
            topItems: ["Beach Burger", "Wings", "Fish & Chips", "Craft Beer Flight"],
            bestFor: "Casual eats & drinks", icon: "fork.knife"),

        // Chatham
        LocalSuggestion(id: "r-chatham-bars-inn", name: "Chatham Bars Inn", type: .restaurant, town: .chatham,
            rating: 4.7, reviewCount: 523, priceLevel: 4,
            description: "Upscale oceanfront dining with farm-to-table menu and impeccable service.",
            topItems: ["Pan-Seared Scallops", "Lobster Thermidor", "Wagyu Steak", "Crème Brûlée"],
            bestFor: "Special occasion", icon: "fork.knife"),
        LocalSuggestion(id: "r-chatham-pier-fish", name: "Chatham Pier Fish Market", type: .restaurant, town: .chatham,
            rating: 4.6, reviewCount: 780, priceLevel: 2,
            description: "Watch fishing boats unload while you eat the freshest seafood on the Cape.",
            topItems: ["Lobster Roll", "Clam Chowder", "Fish & Chips", "Crab Cake"],
            bestFor: "Fresh off the boat", icon: "fork.knife"),
        LocalSuggestion(id: "r-impudent-oyster", name: "The Impudent Oyster", type: .restaurant, town: .chatham,
            rating: 4.5, reviewCount: 645, priceLevel: 3,
            description: "Global seafood in a cozy downtown setting. Creative menu with international flair.",
            topItems: ["Oysters Rockefeller", "Bouillabaisse", "Shrimp Curry", "Key Lime Pie"],
            bestFor: "Creative seafood", icon: "fork.knife"),
        LocalSuggestion(id: "r-chatham-squire", name: "The Chatham Squire", type: .restaurant, town: .chatham,
            rating: 4.3, reviewCount: 920, priceLevel: 2,
            description: "A Chatham institution since 1968. Classic pub atmosphere with great chowder.",
            topItems: ["Clam Chowder", "Fish Sandwich", "Lobster Mac & Cheese", "Draft Beer"],
            bestFor: "Classic pub grub", icon: "fork.knife"),

        // Hyannis
        LocalSuggestion(id: "r-pain-davignon", name: "Pain D'Avignon", type: .restaurant, town: .hyannis,
            rating: 4.6, reviewCount: 492, priceLevel: 3,
            description: "French bakery-café with artisan breads, pastries, and a seasonal bistro menu.",
            topItems: ["Croissant", "Baguette Sandwich", "French Onion Soup", "Croque Monsieur"],
            bestFor: "Brunch & bakery", icon: "fork.knife"),
        LocalSuggestion(id: "r-baxter-fish-n-chips", name: "Baxter's Boathouse Club", type: .restaurant, town: .hyannis,
            rating: 4.4, reviewCount: 1120, priceLevel: 2,
            description: "Iconic harbor-front spot. Casual dockside dining with live entertainment in summer.",
            topItems: ["Lobster Roll", "Fried Clams", "Fish Tacos", "Frozen Drinks"],
            bestFor: "Harbor views", icon: "fork.knife"),
        LocalSuggestion(id: "r-brazilian-grill", name: "Brazilian Grill", type: .restaurant, town: .hyannis,
            rating: 4.5, reviewCount: 390, priceLevel: 2,
            description: "Authentic Brazilian rodizio and buffet. All-you-can-eat meats carved tableside.",
            topItems: ["Picanha", "Chicken Hearts", "Feijoada", "Caipirinha"],
            bestFor: "Meat lovers", icon: "fork.knife"),

        // Provincetown
        LocalSuggestion(id: "r-lobster-pot", name: "The Lobster Pot", type: .restaurant, town: .provincetown,
            rating: 4.6, reviewCount: 1560, priceLevel: 3,
            description: "Legendary Provincetown seafood. Lobster bisque is widely considered the Cape's best.",
            topItems: ["Lobster Bisque", "Baked Stuffed Lobster", "Clam Chowder", "Raw Bar"],
            bestFor: "Legendary bisque", icon: "fork.knife"),
        LocalSuggestion(id: "r-canteen", name: "The Canteen", type: .restaurant, town: .provincetown,
            rating: 4.5, reviewCount: 380, priceLevel: 2,
            description: "Farm-to-table casual spot. Creative takes on New England classics.",
            topItems: ["Lobster Tacos", "Fried Oysters", "Kale Caesar", "Soft Serve"],
            bestFor: "Creative casual", icon: "fork.knife"),
        LocalSuggestion(id: "r-macs-seafood", name: "Mac's Seafood", type: .restaurant, town: .provincetown,
            rating: 4.4, reviewCount: 670, priceLevel: 2,
            description: "Fresh sushi and seafood market. Get it raw, fried, or grilled — all exceptional.",
            topItems: ["Sushi Platter", "Lobster Roll", "Poke Bowl", "Oysters on the Half Shell"],
            bestFor: "Sushi & raw bar", icon: "fork.knife"),

        // Wellfleet
        LocalSuggestion(id: "r-pbs-wellfleet", name: "PB Boulangerie", type: .restaurant, town: .wellfleet,
            rating: 4.8, reviewCount: 445, priceLevel: 3,
            description: "World-class French bakery in Wellfleet. Award-winning pastries and bistro dinners.",
            topItems: ["Pain au Chocolat", "Duck Confit", "Almond Croissant", "Steak Frites"],
            bestFor: "French pastries", icon: "fork.knife"),
        LocalSuggestion(id: "r-moby-dicks", name: "Moby Dick's", type: .restaurant, town: .wellfleet,
            rating: 4.4, reviewCount: 890, priceLevel: 2,
            description: "BYOB seafood shack. Huge portions, paper plates, and the freshest fried clams.",
            topItems: ["Fried Clams", "Lobster Dinner", "Onion Rings", "Corn on the Cob"],
            bestFor: "Seafood shack", icon: "fork.knife"),
        LocalSuggestion(id: "r-beachcomber", name: "The Beachcomber", type: .restaurant, town: .wellfleet,
            rating: 4.3, reviewCount: 720, priceLevel: 2,
            description: "Beach bar in a former lifesaving station. Live music, cocktails, and ocean views.",
            topItems: ["Rum Punch", "Fish Tacos", "Nachos", "Frozen Margarita"],
            bestFor: "Beach bar vibes", icon: "fork.knife"),

        // Brewster
        LocalSuggestion(id: "r-brewster-fish", name: "Brewster Fish House", type: .restaurant, town: .brewster,
            rating: 4.7, reviewCount: 510, priceLevel: 3,
            description: "Tiny, beloved seafood restaurant. No reservations — arrive early or wait. Worth it.",
            topItems: ["Grilled Bluefish", "Pan-Seared Scallops", "Cioppino", "Crème Brûlée"],
            bestFor: "Best-kept secret", icon: "fork.knife"),
        LocalSuggestion(id: "r-cobie", name: "Cobie's", type: .restaurant, town: .brewster,
            rating: 4.5, reviewCount: 620, priceLevel: 1,
            description: "Classic Route 6A clam shack since 1948. Generations of families come here every summer.",
            topItems: ["Fried Clam Plate", "Lobster Roll", "Onion Rings", "Ice Cream"],
            bestFor: "Classic clam shack", icon: "fork.knife"),

        // Falmouth
        LocalSuggestion(id: "r-clam-shack-falmouth", name: "The Clam Shack", type: .restaurant, town: .falmouth,
            rating: 4.5, reviewCount: 780, priceLevel: 2,
            description: "Harborside seafood takeout. Fresh fried seafood with views of the inner harbor.",
            topItems: ["Fried Clams", "Lobster Roll", "Fish & Chips", "Clam Chowder"],
            bestFor: "Harbor takeout", icon: "fork.knife"),
        LocalSuggestion(id: "r-glass-onion", name: "Glass Onion", type: .restaurant, town: .falmouth,
            rating: 4.4, reviewCount: 340, priceLevel: 3,
            description: "Farm-to-table American bistro. Creative cocktails and seasonal menus.",
            topItems: ["Pork Belly", "Local Oysters", "Craft Cocktails", "Seasonal Risotto"],
            bestFor: "Farm-to-table", icon: "fork.knife"),

        // Sandwich
        LocalSuggestion(id: "r-seafood-sams", name: "Seafood Sam's", type: .restaurant, town: .sandwich,
            rating: 4.2, reviewCount: 560, priceLevel: 1,
            description: "Family-friendly seafood near the canal. Great for kids with generous portions.",
            topItems: ["Kids Fish & Chips", "Lobster Roll", "Clam Strips", "Ice Cream"],
            bestFor: "Family-friendly", icon: "fork.knife"),
        LocalSuggestion(id: "r-belfry-bistro", name: "Belfry Inn & Bistro", type: .restaurant, town: .sandwich,
            rating: 4.6, reviewCount: 290, priceLevel: 3,
            description: "Fine dining in a restored church. Stained glass windows and creative New American.",
            topItems: ["Duck Breast", "Lobster Risotto", "Filet Mignon", "Molten Chocolate"],
            bestFor: "Unique setting", icon: "fork.knife"),

        // Dennis/Yarmouth
        LocalSuggestion(id: "r-captain-frostys", name: "Captain Frosty's", type: .restaurant, town: .dennisYarmouth,
            rating: 4.6, reviewCount: 920, priceLevel: 1,
            description: "Best fried clams on the mid-Cape. Order at the window, eat at picnic tables.",
            topItems: ["Fried Clams", "Onion Rings", "Lobster Roll", "Soft Serve"],
            bestFor: "Fried clams", icon: "fork.knife"),
        LocalSuggestion(id: "r-skipper-restaurant", name: "Skipper Restaurant", type: .restaurant, town: .dennisYarmouth,
            rating: 4.3, reviewCount: 510, priceLevel: 2,
            description: "Oceanfront dining on Nantucket Sound since 1936. Classic Cape Cod seafood.",
            topItems: ["Baked Stuffed Lobster", "Clam Chowder", "Prime Rib", "Sunset Views"],
            bestFor: "Oceanfront classic", icon: "fork.knife"),

        // Truro
        LocalSuggestion(id: "r-blackfish", name: "Blackfish", type: .restaurant, town: .truro,
            rating: 4.7, reviewCount: 310, priceLevel: 3,
            description: "Upscale comfort food in a restored blacksmith shop. Outstanding wine list.",
            topItems: ["Pan-Roasted Cod", "Braised Short Ribs", "Oyster Stew", "Apple Crisp"],
            bestFor: "Upscale comfort", icon: "fork.knife"),

        // Eastham
        LocalSuggestion(id: "r-arnolds-lobster", name: "Arnold's Lobster & Clam Bar", type: .restaurant, town: .eastham,
            rating: 4.5, reviewCount: 1340, priceLevel: 2,
            description: "Cape Cod's busiest clam bar. Mini golf next door keeps kids happy while you wait.",
            topItems: ["Lobster Roll", "Fried Clams", "Raw Bar", "Mini Golf"],
            bestFor: "Family clam bar", icon: "fork.knife"),

        // Harwich
        LocalSuggestion(id: "r-brax-landing", name: "Brax Landing", type: .restaurant, town: .harwich,
            rating: 4.4, reviewCount: 480, priceLevel: 2,
            description: "Waterfront dining on Saquatucket Harbor. Watch the boats come and go.",
            topItems: ["Lobster Roll", "Stuffed Quahog", "Grilled Swordfish", "Draft Beer"],
            bestFor: "Harbor dining", icon: "fork.knife"),
    ]

    // MARK: - Tourist Attractions

    static let attractions: [LocalSuggestion] = [
        // Orleans
        LocalSuggestion(id: "a-nauset-beach", name: "Nauset Beach", type: .attraction, town: .orleans,
            rating: 4.8, reviewCount: 2100, priceLevel: 1,
            description: "10-mile barrier beach with dramatic surf. Great for body surfing and long walks.",
            topItems: ["Body Surfing", "Beach Walking", "Sunset Views", "Seal Watching"],
            bestFor: "Iconic beach", icon: "water.waves"),
        LocalSuggestion(id: "a-orleans-kayak", name: "Nauset Marsh Kayaking", type: .attraction, town: .orleans,
            rating: 4.7, reviewCount: 340, priceLevel: 2,
            description: "Paddle through pristine salt marshes. Spot herons, egrets, and harbor seals.",
            topItems: ["Guided Tours", "Wildlife Spotting", "Sunset Paddles", "Seal Encounters"],
            bestFor: "Nature adventure", icon: "figure.rowing"),

        // Chatham
        LocalSuggestion(id: "a-chatham-lighthouse", name: "Chatham Lighthouse", type: .attraction, town: .chatham,
            rating: 4.7, reviewCount: 1890, priceLevel: 0,
            description: "Iconic lighthouse with panoramic views. Watch seals basking on nearby sandbars.",
            topItems: ["Lighthouse Views", "Seal Watching", "Photo Ops", "Free Parking"],
            bestFor: "Must-see landmark", icon: "lighthouse.fill"),
        LocalSuggestion(id: "a-chatham-main-st", name: "Chatham Main Street", type: .attraction, town: .chatham,
            rating: 4.6, reviewCount: 1450, priceLevel: 0,
            description: "Charming downtown with boutiques, galleries, and Friday night band concerts.",
            topItems: ["Boutique Shopping", "Art Galleries", "Band Concert", "Ice Cream"],
            bestFor: "Town strolling", icon: "storefront.fill"),
        LocalSuggestion(id: "a-monomoy-wildlife", name: "Monomoy National Wildlife Refuge", type: .attraction, town: .chatham,
            rating: 4.8, reviewCount: 560, priceLevel: 1,
            description: "2,750-acre refuge with guided seal cruises. One of the largest seal colonies on the East Coast.",
            topItems: ["Seal Cruise", "Bird Watching", "Beach Walk", "Photography"],
            bestFor: "Wildlife lovers", icon: "binoculars.fill"),

        // Hyannis
        LocalSuggestion(id: "a-jfk-museum", name: "JFK Hyannis Museum", type: .attraction, town: .hyannis,
            rating: 4.5, reviewCount: 890, priceLevel: 2,
            description: "Multimedia tribute to JFK's Cape Cod years. Photos, videos, and personal artifacts.",
            topItems: ["JFK Exhibits", "Photo Gallery", "Gift Shop", "Walking Tour Map"],
            bestFor: "History buffs", icon: "building.columns.fill"),
        LocalSuggestion(id: "a-hyannis-harbor", name: "Hyannis Harbor & Main Street", type: .attraction, town: .hyannis,
            rating: 4.4, reviewCount: 1200, priceLevel: 0,
            description: "Vibrant harbor with island ferries, shops, and restaurants. Gateway to Nantucket.",
            topItems: ["Island Ferries", "Shopping", "Harbor Cruise", "Dining"],
            bestFor: "Town center", icon: "ferry.fill"),
        LocalSuggestion(id: "a-cape-cod-chips", name: "Cape Cod Potato Chips Factory", type: .attraction, town: .hyannis,
            rating: 4.3, reviewCount: 1650, priceLevel: 0,
            description: "Free self-guided factory tour. Watch chips being made and grab free samples.",
            topItems: ["Factory Tour", "Free Samples", "Gift Shop", "Photo Ops"],
            bestFor: "Free family fun", icon: "gift.fill"),

        // Provincetown
        LocalSuggestion(id: "a-pilgrim-monument", name: "Pilgrim Monument & Museum", type: .attraction, town: .provincetown,
            rating: 4.6, reviewCount: 1340, priceLevel: 2,
            description: "Tallest all-granite structure in the US. Climb 116 steps for 360-degree Cape views.",
            topItems: ["Tower Climb", "Museum Exhibits", "Panoramic Views", "History"],
            bestFor: "Panoramic views", icon: "building.columns.fill"),
        LocalSuggestion(id: "a-whale-watching", name: "Whale Watch Cruises", type: .attraction, town: .provincetown,
            rating: 4.7, reviewCount: 2200, priceLevel: 3,
            description: "Stellwagen Bank whale watching. Humpbacks, fin whales, and dolphins guaranteed.",
            topItems: ["Humpback Whales", "Dolphins", "Naturalist Guide", "3-4 Hour Trip"],
            bestFor: "Must-do experience", icon: "water.waves"),
        LocalSuggestion(id: "a-commercial-st", name: "Commercial Street", type: .attraction, town: .provincetown,
            rating: 4.8, reviewCount: 3100, priceLevel: 0,
            description: "P-town's vibrant main drag. Art galleries, drag shows, street performers, and boutiques.",
            topItems: ["Art Galleries", "Street Performers", "Shopping", "People Watching"],
            bestFor: "Vibrant culture", icon: "paintpalette.fill"),

        // Wellfleet
        LocalSuggestion(id: "a-wellfleet-drive-in", name: "Wellfleet Drive-In Theatre", type: .attraction, town: .wellfleet,
            rating: 4.6, reviewCount: 980, priceLevel: 2,
            description: "One of the last drive-in theaters in MA. Double features under the stars plus a flea market.",
            topItems: ["Double Feature", "Snack Bar", "Flea Market", "Mini Golf"],
            bestFor: "Nostalgic nights", icon: "film.fill"),
        LocalSuggestion(id: "a-wellfleet-oysters", name: "Wellfleet Oyster Farms Tour", type: .attraction, town: .wellfleet,
            rating: 4.7, reviewCount: 320, priceLevel: 2,
            description: "Tour working oyster grants at low tide. Learn how Wellfleet oysters are cultivated.",
            topItems: ["Oyster Tasting", "Farm Tour", "Low Tide Walk", "Local History"],
            bestFor: "Foodie adventure", icon: "drop.fill"),

        // Brewster
        LocalSuggestion(id: "a-nickerson-state-park", name: "Nickerson State Park", type: .attraction, town: .brewster,
            rating: 4.7, reviewCount: 1560, priceLevel: 1,
            description: "1,900 acres of forests, ponds, and trails. Swimming, biking, and camping.",
            topItems: ["Freshwater Swimming", "Bike Trails", "Camping", "Fishing"],
            bestFor: "Nature escape", icon: "tree.fill"),
        LocalSuggestion(id: "a-cape-cod-museum", name: "Cape Cod Museum of Natural History", type: .attraction, town: .brewster,
            rating: 4.5, reviewCount: 670, priceLevel: 2,
            description: "Interactive nature exhibits and boardwalk trails through salt marshes.",
            topItems: ["Nature Trails", "Live Animals", "Kids Programs", "Bird Watching"],
            bestFor: "Educational fun", icon: "binoculars.fill"),

        // Falmouth
        LocalSuggestion(id: "a-shining-sea-bikeway", name: "Shining Sea Bikeway", type: .attraction, town: .falmouth,
            rating: 4.8, reviewCount: 1890, priceLevel: 0,
            description: "10.7-mile paved bike path from Woods Hole to North Falmouth. Ocean views galore.",
            topItems: ["Bike Riding", "Ocean Views", "Bird Sanctuary", "Beach Access"],
            bestFor: "Scenic biking", icon: "bicycle"),
        LocalSuggestion(id: "a-woods-hole", name: "Woods Hole Village", type: .attraction, town: .falmouth,
            rating: 4.6, reviewCount: 1100, priceLevel: 0,
            description: "Charming science village. Home to WHOI, MBL, and the Martha's Vineyard ferry.",
            topItems: ["WHOI Exhibit Center", "Aquarium", "Ferry to MV", "Village Walk"],
            bestFor: "Science & ferries", icon: "building.columns.fill"),

        // Sandwich
        LocalSuggestion(id: "a-sandwich-boardwalk", name: "Sandwich Boardwalk", type: .attraction, town: .sandwich,
            rating: 4.7, reviewCount: 2300, priceLevel: 0,
            description: "1,350-foot boardwalk over marshes to Town Neck Beach. Spectacular sunsets.",
            topItems: ["Sunset Walk", "Marsh Views", "Beach Access", "Photography"],
            bestFor: "Sunset strolls", icon: "sun.horizon.fill"),
        LocalSuggestion(id: "a-heritage-museum", name: "Heritage Museums & Gardens", type: .attraction, town: .sandwich,
            rating: 4.6, reviewCount: 1020, priceLevel: 3,
            description: "100 acres of gardens, vintage cars, folk art, and a working carousel.",
            topItems: ["Vintage Cars", "Gardens", "Carousel Ride", "Art Exhibits"],
            bestFor: "Gardens & history", icon: "leaf.fill"),

        // Dennis/Yarmouth
        LocalSuggestion(id: "a-cape-playhouse", name: "Cape Playhouse", type: .attraction, town: .dennisYarmouth,
            rating: 4.5, reviewCount: 780, priceLevel: 3,
            description: "America's oldest professional summer theater. Broadway-quality shows since 1927.",
            topItems: ["Live Theater", "Musicals", "Gift Shop", "Historic Venue"],
            bestFor: "Live entertainment", icon: "theatermasks.fill"),
        LocalSuggestion(id: "a-bass-hole-boardwalk", name: "Bass Hole Boardwalk", type: .attraction, town: .dennisYarmouth,
            rating: 4.6, reviewCount: 1340, priceLevel: 0,
            description: "Quiet boardwalk through salt marsh to Cape Cod Bay. Best sunset spot on the mid-Cape.",
            topItems: ["Sunset Views", "Bird Watching", "Marsh Walk", "Photography"],
            bestFor: "Hidden gem sunsets", icon: "sun.horizon.fill"),

        // Truro
        LocalSuggestion(id: "a-highland-lighthouse", name: "Highland Lighthouse", type: .attraction, town: .truro,
            rating: 4.6, reviewCount: 670, priceLevel: 1,
            description: "Cape Cod's oldest and tallest lighthouse. Climb to the top for Outer Cape panoramas.",
            topItems: ["Lighthouse Tour", "Ocean Views", "Golf Course", "Photo Ops"],
            bestFor: "Lighthouse lovers", icon: "lighthouse.fill"),
        LocalSuggestion(id: "a-corn-hill-beach", name: "Corn Hill Beach", type: .attraction, town: .truro,
            rating: 4.7, reviewCount: 540, priceLevel: 1,
            description: "Quiet bayside beach with calm waters and legendary sunsets. Less crowded than most.",
            topItems: ["Calm Swimming", "Sunsets", "Shell Collecting", "Quiet Beach"],
            bestFor: "Peaceful retreat", icon: "sun.max.fill"),

        // Eastham
        LocalSuggestion(id: "a-fort-hill", name: "Fort Hill", type: .attraction, town: .eastham,
            rating: 4.8, reviewCount: 1200, priceLevel: 0,
            description: "Sweeping views of Nauset Marsh from the bluffs. Easy trail through Red Maple Swamp.",
            topItems: ["Marsh Views", "Red Maple Trail", "Historic House", "Bird Watching"],
            bestFor: "Easy nature walk", icon: "mountain.2.fill"),
        LocalSuggestion(id: "a-coast-guard-beach", name: "Coast Guard Beach", type: .attraction, town: .eastham,
            rating: 4.8, reviewCount: 1890, priceLevel: 1,
            description: "One of America's best beaches per Dr. Beach. Dramatic dunes and great bodysurfing.",
            topItems: ["Body Surfing", "Seal Spotting", "Dune Views", "Shuttle Bus"],
            bestFor: "Top-rated beach", icon: "water.waves"),

        // Harwich
        LocalSuggestion(id: "a-cape-cod-rail-trail", name: "Cape Cod Rail Trail", type: .attraction, town: .harwich,
            rating: 4.7, reviewCount: 2400, priceLevel: 0,
            description: "25-mile paved bike trail from Dennis to Wellfleet. Cape Cod's best cycling route.",
            topItems: ["Biking", "Pond Access", "Scenic Views", "Bike Rentals"],
            bestFor: "Cycling adventure", icon: "bicycle"),
        LocalSuggestion(id: "a-red-river-beach", name: "Red River Beach", type: .attraction, town: .harwich,
            rating: 4.5, reviewCount: 480, priceLevel: 1,
            description: "Calm Nantucket Sound beach perfect for families. Warm water and gentle waves.",
            topItems: ["Family Swimming", "Warm Water", "Gentle Waves", "Parking"],
            bestFor: "Family beach", icon: "water.waves"),
    ]
}

// swiftlint:enable type_body_length file_length
